name: cherry-pick into target branches

on:
  workflow_dispatch:
  pull_request:
    # types: [closed]

env:
  FAILED_BRANCHES:

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    strategy:
      matrix:
        label: ${{ github.event.pull_request.labels.*.name }}
    outputs:
      failed_branches: ${{ steps.update_failed_branches.outputs.failed_branches }}

    steps:
    - name: Get branch from label
      id: branch_name
      run: |
        echo "::set-output name=branch::$(echo ${{ matrix.label }} | sed -n 's/target: \([0-9]*.x\).*/\1/p')"

    - uses: actions/checkout@v3
      if: steps.branch_name.outputs.branch
      with:
        fetch-depth: 0

    - name: Cherry-pick changes into maintenance ${{ steps.branch_name.outputs.branch }}
      if: steps.branch_name.outputs.branch
      run: |
        git checkout ${{ steps.branch_name.outputs.branch }}
        git -c user.name="cherry-picker" -c user.email="cherry.picker@sbb.ch" cherry-pick ${{ github.sha }}
        git push

    - name: Update failed branches
      id: update_failed_branches
      if: ${{ failure() }}
      run: |
        echo "FAILED_BRANCHES$=$(echo ${{ env.FAILED_BRANCHES }} ${{ steps.branch_name.outputs.branch }})" >> $GITHUB_ENV
        echo "::set-output name=failed_branches::${{ env.FAILED_BRANCHES }}"


  update_maintenance_ticket:
    runs-on: ubuntu-latest
    needs: cherry_pick
    if: always() && needs.cherry_pick.result == 'failure'

    steps:
    - uses: actions/setup-node@v3
      if: needs.cherry_pick.outputs.failed_branches != ''
      with:
        node-version: 16

    - uses: ./.github/actions/yarn-install
      if: needs.cherry_pick.outputs.failed_branches != ''

    - name: Update maintenance issue
      if: needs.cherry_pick.outputs.failed_branches != ''
      run: yarn ts-node scripts/update-maintenance-issue.ts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        FAILED_BRANCHES: ${{ needs.cherry_pick.outputs.failed_branches }}
