name: cherry-pick into target branches

on:
  workflow_dispatch:
  pull_request:
    # types: [closed]

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    strategy:
      matrix:
        label: ${{github.event.pull_request.labels.*.name}}
    outputs:
      output: ${{ steps.cherry_pick.outputs.output }}

    steps:
    - name: Get branch from label
      id: branch_name
      run: |
        echo "::set-output name=branch::$(echo ${{ matrix.label }} | sed -n 's/target: \([0-9]*.x\).*/\1/p')"

    - uses: actions/checkout@v3
      if: steps.branch_name.outputs.branch
      with:
        fetch-depth: 0

    - name: Cherry-pick changes into maintenance ${{ matrix.label }}
      id: cherry_pick
      if: steps.branch_name.outputs.branch
      run: |
        git checkout ${{ matrix.label }}
        echo "::set-output name=output::$(git -c user.name="cherry-picker" \
          -c user.email="cherry.picker@sbb.ch" cherry-pick ${{ github.sha }} | xargs)"
        git push

    - uses: actions/setup-node@v3
      if: ${{ contains(steps.cherry_pick.outputs.output, 'CONFLICT') }}
      with:
        node-version: 16

    - uses: ./.github/actions/yarn-install
      if: ${{ contains(steps.cherry_pick.outputs.output, 'CONFLICT') }}

    - name: "Update maintenance issue"
      if: ${{ contains(steps.cherry_pick.outputs.output, 'CONFLICT') }}
      run: yarn ts-node scripts/update-maintenance-issue.ts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        TARGET_BRANCH: ${{ matrix.label }}
