name: Add or remove maintenance labels

on:
  pull_request:
    types: [opened, edited]
    branches: [master]

env:
  TARGET_RELEASE: 13.x

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Add target label"
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ !contains(github.event.pull_request.description, 'BREAKING_CHANGE:') }}
        with:
          labels: "target: ${{ env.TARGET_RELEASE }}"
      - name: "Remove target label"
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ contains(github.event.pull_request.description, 'BREAKING_CHANGE:') }}
        with:
          labels: "target: ${{ env.TARGET_RELEASE }}"
