name: cherry-pick on maintenance branch

on:
  pull_request:
    types: [closed]

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.cherry_pick.outputs.output }}
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'target: maintenance')
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: cherry-pick
      id: cherry_pick
      run: |
        git checkout maintenance
        echo "::set-output name=output::$(git -c user.name="cherry-picker" 
          -c user.email="cherry-picker@acme.org" cherry-pick ${{ github.sha }} | xargs)"
        git push
  update_issue:
    runs-on: ubuntu-latest
    needs: cherry_pick
    if: ${{ contains(needs.cherry_pick.outputs.output, 'CONFLICT') }}
    steps:
    - uses: actions/checkout@v3
    - name: Create branch for pull request
      run: |
        git branch ${{ github.event.pull_request.head.ref }}-maintenance ${{ github.sha }}
        git push origin ${{ github.event.pull_request.head.ref }}-maintenance
    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: ${{ github.event.pull_request.head.ref }}-maintenance
        base: maintenance
        title: "maintenance: ${{ github.event.pull_request.title }}"
        body: needs.cherry_pick.outputs.output
