name: cherry-pick into target branches

on:
  workflow_dispatch:
  pull_request:
    # types: [closed]

env:
  FAILED_BRANCHES:

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    strategy:
      matrix:
        label: ${{github.event.pull_request.labels.*.name}}
    outputs:
      output: ${{ steps.cherry_pick.outputs.output }}

    steps:
    - name: Get branch from label
      id: branch_name
      run: |
        echo "::set-output name=branch::$(echo ${{ matrix.label }} | sed -n 's/target: \([0-9]*.x\).*/\1/p')"

    - uses: actions/checkout@v3
      if: steps.branch_name.outputs.branch
      with:
        fetch-depth: 0

    - name: Cherry-pick changes into maintenance ${{ steps.branch_name.outputs.branch }}
      id: cherry_pick
      if: steps.branch_name.outputs.branch
      run: |
        git checkout ${{ steps.branch_name.outputs.branch }}
        git -c user.name="cherry-picker" -c user.email="cherry.picker@sbb.ch" cherry-pick ${{ github.sha }}
        git push

    - name: Update failed branches
      if: ${{ failure() }}
      run: echo "FAILED_BRANCHES$=$(echo ${{ env.FAILED_BRANCHES }} ${{ steps.branch_name.outputs.branch }})" >> $GITHUB_ENV

  update_maintenance_ticket:
    runs-on: ubuntu-latest
    needs: [ cherry_pick ]
    if: always() && needs.cherry_pick.result == 'failure'
    steps:
    - uses: actions/setup-node@v3
      if: ${{ env.FAILED_BRANCHES != '' }}
      with:
        node-version: 16

    - uses: ./.github/actions/yarn-install
      if: ${{ env.FAILED_BRANCHES != '' }}

    - name: "Update maintenance issue"
      if: ${{ env.FAILED_BRANCHES != '' }}
      run: yarn ts-node scripts/update-maintenance-issue.ts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        FAILED_BRANCHES: ${{ env.FAILED_BRANCHES }}
