name: cherry-pick changelog into default branch

on:
  push:
    tags:
      - '*'

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    outputs:
      failed_release_version: ${{ steps.cherry_pick_error.failed_release_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Get commit for tag
        run: echo "TAG_COMMIT=$(git rev-list -n 1 ${{ env.RELEASE_VERSION }})" >> $GITHUB_ENV
      - name: Cherry-pick CHANGELOG.md into ${{ github.event.repository.default_branch }}
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git checkout ${{ github.event.repository.default_branch }}
          git cherry-pick --no-commit ${{ env.TAG_COMMIT }}
          git reset
          git add CHANGELOG.md
          git checkout .
          git commit -m "chore: update changelog"
          git push
      - name: Handling error
        if: ${{ failure() }}
        id: cherry_pick_error
        run: |
          echo "::set-output name=failed_release_version::$(echo ${{ env.RELEASE_VERSION }})"

  update_maintenance_issue:
    runs-on: ubuntu-latest
    needs: cherry_pick
    if: always() && needs.cherry_pick.result == 'failure'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        if: needs.cherry_pick.outputs.failed_release_version
        with:
          node-version: 16
      - uses: ./.github/actions/yarn-install
        if: needs.cherry_pick.outputs.failed_release_version
      - name: Update maintenance issue
        if: needs.cherry_pick.outputs.failed_release_version
        run: yarn ts-node scripts/update-maintenance-issue.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FAILED_RELEASE: ${{ needs.cherry_pick.outputs.failed_release_version }}
