name: cherry-pick on maintenance branch

on:
  pull_request:
    types: [closed]

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.cherry_pick.outputs.output }}
      exit_code: ${{ steps.cherry_pick.outputs.exit_code }}
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'target: maintenance')
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: cherry-pick
      id: cherry_pick
      run: |
        git checkout maintenance
        echo "::set-output name=output::$(git -c user.name="cerry-picker" -c user.email="cherry-picker@acme.org" cherry-pick ${{ github.sha }})"
        echo "::set-output name=exit_code::$(echo $?)"
        git push
  pull_request:
    runs-on: ubuntu-latest
    needs: cherry_pick
    # if: needs.cherry_pick.outputs.exit_code == '0'
    steps:
    - uses: actions/checkout@v3
    - name: Create branch for pull request
      run: |
        git checkout branch  ${{ github.event.pull_request.head.ref }}-maintenance ${{ github.sha }}
        git push
    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: ${{ github.event.pull_request.head.ref }}-maintenance
        title: "maintenance: ${{ github.event.pull_request.title }}"
        body: needs.cherry_pick.outputs.output

