name: cherry-pick changelog into default branch

on:
  push:
    tags:
      - '*'

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Get commit for tag
        run: echo "TAG_COMMIT=$(git rev-list -n 1 ${{ env.RELEASE_VERSION }})" >> $GITHUB_ENV
      - name: Cherry-pick CHANGELOG.md into ${{ github.event.repository.default_branch }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email="github-actions@github.com"
          git checkout ${{ github.event.repository.default_branch }}
          git cherry-pick --no-commit ${{ env.TAG_COMMIT }})
          git add CHANGELOG.md
          git checkout .
          git commit -m "chore: update changelog"
          git push
