name: cherry-pick on maintenance branch

on:
  pull_request:
    types: [closed]

jobs:
  cherry_pick:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: cherry-pick
      run: |
        git checkout maintenance
        git cherry=pick ${{github.sha}}
